# Generated by Django 2.2.4 on 2019-08-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='answer_selected',
            field=models.BooleanField(default='False'),
        ),
    ]
