# Generated by Django 2.2.4 on 2019-08-13 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0002_quiz_answer_selected'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='answer_selected',
        ),
    ]
